Questions = [
    "Jakie zwierzę można spotkać podczas spaceru przez pola?",
    "Co jest w pociągu i w domu?",
    "Co potrafią robić ptaki?",
    "Miejski ptak.",
    "Leży na biurku.",
    "Co rozwiązujemy chociaż tego nie zawiązujemy?",
    "Co napełnia się gazem?",
    "Jaki rok nie zaczyna się od pierwszego stycznia?",
    "Jaki specjalny wagon może znajdować się w składzie pociągu?",
    "Wąsate zwierze?",
    "Czym może być pokryty dach?",
    "Wymień elementy dekoracji wnętrz?",
    "Jakie ciasto kojarzy się z wizytą u babci?",
    "Co ludzie często gubią?",
    "Co pijemy do śniadania?",
    "Europejskie państwo większe od Polski.",
    "Przykład rośliny doniczkowej",
    "Do jakiej ryby można porównać człowieka?",
    "Czym rózni się kura od koguta?",
    "Jakie klawisze oprócz literowych znajdują się na klawiaturze?",
    "Co w przenośni może być czarne?",
    "Imię męskie zawierające cząstkę sław.",
    "Co jest dostarczane do mieszkań za pomocą kabli?",
    "Najbardziej znane polskie jezioro.",
    "Dodaj litery do słowa -matka- tak, by utworzyć nowy wyraz."
]

Answers = [
    ['krowę', 'zająca', 'sarnę', 'bociana'],
    ['okna', 'drzwi', 'toaleta', 'fotele', 'ludzie'],
    ['srać', 'latać', 'śpiewać', 'znosić jaja'],
    ['gołąb', 'wróbel', 'sikorka'],
    ['laptop', 'zeszyt', 'długopis', 'marihuana', 'szlugi'],
    ['zagadkę', 'krzyżówkę', 'zadanie', 'równanie', 'problem'],
    ['butlę', 'zapalniczkę', 'bak', 'balon'],
    ['szkolny', 'akademicki', 'liturgiczny', 'żydowski'],
    ['sypialny', 'pocztowy', 'restauracyjny', 'do przewozu rowerów'],
    ['kot', 'mysz', 'tygrys', 'lew'],
    ['dachówka', 'papa', 'blacha', 'eternit'],
    ['zasłony', 'firanki', 'lampa', 'obraz'],
    ['sernik', 'szarlotka', 'piernik', 'ciasto drożdżowe', 'makowiec', 'keks']
    ['klucze', 'pieniadze', 'dokumenty', 'parasol', 'czapke']
    ['kawe', 'herbate', 'mleko', 'kakao', 'sok']
    ['Niemcy', 'Francja', 'Wielka Brytania', 'Hiszpania', 'Szwecja'],
    ['paproc', 'storczyk', 'fikus', 'dracena', 'bluszcz'],
    ['do rekina', 'do leszcza', 'do piranii', 'do plotki', 'do piskorza'],
    ['znoszeniem', 'plcia', 'upierzeniem', 'odglosami'],
    ['enter', 'spacja', 'shift', 'alt'],
    ['mysli', 'godzina', 'lista', 'robota'],
    ['Stanisław', 'Bolesław', 'Bronisław'],
    ['prad', 'internet', 'telewizja'],
    ['Sniardwy', 'Mamry', 'Wigry'],
    ['dyplomatka', 'armatka', 'szmatka']
]

Hints = [
    ['mleko daje', 'długie uszy ma', 'zgrabna i skoczna', 'jest biały'],
    ['widac przez nie swiat', 'mozna przez nie wyjsc na swat', 'krol chodzi tam piechota', 'moga byc bujane choc nie w pociagach', '7 miliardow ich lazi a bedzie wiecej'],
    ['robic po katach', 'unosic sie w powietrzu', 'zaklocac cisze nocna', 'produkowac materialy na jajecznice'],
    ['obsrywa mi parapet', 'elemel(ek)', 'rich bitch [bogatka jest]'],
    ['przenosny konkuter', 'miejsce na notatki', 'cos do robienia notatek', '420', '20 w paczce, przynajmniej na start'],
    ['zadaje ja sfinks', 'lubie rozwiazac jedna na kiblu', 'jest ich duzo w podreczniku do matematyki', '... matematyczne', 'jak masz jakis to zbierasz wpierdol'],
    ['do kuchenki gazowej', 'do odpalania szluga', 'w samochodzie', 'moze byc meteorologiczny'],
    ['2 + 2 = 4', 'Alma Mater', 'publiczna forma kultu religijnego', 'Szalom!'],
    ['chrapu chrap', 'lecą listy lecą', 'om nom nom nom', 'tam przechowasz swoje dwa kółka'],
    ['duże i małe, dzikie i w domu', 'a kysz', 'strzeż się Mowgli', 'dzierży koronę'],
    ['małe kawałki', 'nagrzewa się szybko', 'do widzenia', 'trzeba wymienić bo azbest'],
    ['nie widać co się dzieje', 'białe i delikatne', 'jasno wszędzie!', 'namalowane, można oglądać'],
    ['zaczyna się od mleka', 'najpierw są jabłka', 'z korzenną przyprawą', 'trzeba dużo mieszać', 'czerwone kwiaty', 'mnóstwo kolorowych bakalii'],
    ['otwieramy', 'szczęścia nie dają', 'papiery, papiery', 'schronienie przed kapuśniakiem', 'kiedy zimno jest na głowie'],
    ['otwiera oczy', 'zawiera tiaminę', 'muuuu', 'muuuu i tropikalne ziarna', 'wyciśnięty z owoców i warzyw'],
    ['ich liebe alkohol', 'łapać ślimaka!', 'monarchia i wielki Ben', 'ole', 'stamtąd pochodzi Pippi'],
    ['z legendarnym kwiatem', 'inaczej orchidea', '..... psikus', 'wonna, obrzeżona, Sandera', 'wije się wije'],
    ['wielkie szczęki', 'całkiem słabo', 'groźne rybki', 'niepozorne', 'wije się jak....'],
    ['z góry', 'są tylko dwie!/?', 'powłoka kury lub koguta', 'ko, ko ko, kukuryku'],
    ['potwierdzenie', 'przerwa', 'zmieniamy małe na duże', 'uruchamia polskie znaki'],
    ['takie w głowie', 'na tarczy zegara', 'wyszczególnienie', 'inaczej praca'],
    ['Moniuszko', 'Chrobry', 'Geremek'],
    ['napędza urządzenia', 'łączymy się nim z eRepublik', 'oglądamy'],
    ['największe', 'drugie pod względem powierzchni jezioro w Polsce', 'jak rower składak'],
    ['kobieta dyplomata', 'mała armata', 'do wycierania']
]

Points = [
    [47, 22, 19, 12],
    [39, 19, 17, 15, 10],
    [47, 22, 19, 12],
    [58, 26, 16],
    [39, 19, 17, 15, 10],
    [39, 19, 17, 15, 10],
    [47, 22, 19, 12],
    [30, 20, 10, 5],
    [30, 20, 10, 5],
    [30, 20, 10, 5],
    [30, 20, 10, 5],
    [30, 20, 10, 5],
    [30, 22, 17, 11, 10, 5],
    [25, 19, 16, 14, 11],
    [32, 30, 17, 15, 4],
    [52, 19, 13, 11, 3],
    [41, 35, 14, 6, 5],
    [39, 23, 20, 14, 5],
    [35, 30, 10, 5],
    [30, 20, 10, 5],
    [37, 33, 19, 5],
    [58, 26, 16],
    [58, 26, 16],
    [58, 26, 16],
    [58, 26, 16]
]