Colors = [
    'Porzeczkowi', 'Śliwkowi', 'Musztardowi', 'Kalafiorowi', 'Niebiescy', 'Miętowi', 'Pomarańczowi', 'Karmazynowi', 'Kobaltowi',
    'Limonkowi', 'Harnaś Rules', 'Żubrówka Team', 'Fani Erepublik', 'Plato To Penis'    
]

Puns = [
    'Wiecie dlaczego bocian stoi na jednej nodze?\nBo jakby ja podniósł to by sie na dziób wywalił.',
    'Skąd pochodzi random.w?\nZ Bytomia.',
    'Po czym jest maxiu?\nPo krokodylu.',
    'Dlaczego w Białymstoku nie nosi sie jajek na święcenie?\nBo Uzury je Zezre.'
]

Questions = [
    "Co lata choć nie ma silnika?",
    "Postać z Zemsty Aleksandra Fredry.",
    "Jednowyrazowa komenda wojskowa.",
    "Skandynawska stolica.",
    "Gdzie najłatwiej nawiązać trwałe przyjaźnie?",
    "Co oprócz dóbr materialnych można odziedziczyć?",
    "Jaki mozna mieć humor?",
    "Co bywa dołączane do kobiecych czasopism?",
    "Ktoś kto dopiero zdobywa doświadczenie w danym zawodzie.",
    "Jakiego typu kartki okolicznościowe kupujemy najczęściej?",
    "Jaki lub czego bywa słup?",
    "Na jakiej akademii można studiować?",
    "Co może być ustne?",
    "Co robi się z mleka?",
    "Czego może być czubek?",
    "Wymień polską rzekę na literę B.",
    "Jakie zakazy umieszczane są w pociągach?",
    "Przy wykonywaniu którego zawodu dobrze być mistrzem słowa?",
    "Ulubione miejsce spaceru.",
    "Jajka których ptaków, oprócz kurzych, można jeść?",
    "Co przygotowuje się w przeddzień świąt wielkanocnych?",
    "Co widzimy spoglądając w niebo?",
    "Co można znaleźć w jajku?",
    "W czym bywa herbata?",
    "Do czego można dojść nie używając nóg?",
    "W jakiej postaci jadamy ogórki?",
    "Czego zazwyczaj nie reklamuje się w telewizji i radiu?",
    "Potocznie ukraść.",
    "Jadalna, jasna bulwa.",
    "Co powinno znajdować się na każdym dworcu?",
    "Który ptak zabrał głos w wierszu Juliana Tuwima - Ptasie Radio?",
    "Zawód do którego potrzeba powołania.",
    "Włoski wulkan.",
    "Zwierzę z krótkimi łapkami.",
    "Czego można być królową?",
    "Polskie miasto na literę Ł.",
    "Czego nie pozwalamy dotykać małym dzieciom?",
    "Podaj przykład wodnika.",
    "Co ludzie sprawdzają żeby przekonać się czy jest prawdziwe?",
    "Wymień miejsce w którym zwykle jest bardzo głośno.",
    "Wymień książkę, którą wielu ludzi ma, ale rzadko do niej zagląda.",
    "Wymień słowo, którym określamy osobę niedbałą.",
    "Co jest lub bywa ciężkie?",
    "Wymień zwierzę z przysłowia.",
    "Co jest lub powinno być chronione?",
    "Wymień polskie miasto o dwuczłonowej nazwie.",
    "Co możemy zbierać w lesie?",
    "Wymień znanego wąsacza.",
    "Daj przykład czegoś kwaśnego.",
    "Co jest na placu zabaw?",
    "Co wykonujemy?",
    "Co może mieć i spódnica i bluzka?",
    "Kto pracuje w niedzielę i święta?",
    "Jak nazywamy włosy na twarzy?",
    "Wymień sport pozwalający spalić dużo kalorii.",
]

Answers = [
    ['ptak', 'mucha', 'motyl', 'lotnia', 'nietoperz', 'biedronka'],
    ['Papkin', 'Rejent', 'Cześnik', 'Podstolina', 'Dyndalski', 'Klara'],
    ['baczność', 'spocznij', 'wystąp', 'powstań', 'padnij'],
    ['Sztokholm', 'Oslo', 'Kopenhaga'],
    ['w szkole', 'na studiach', 'w pracy', 'w piaskownicy', 'w przedszkolu', 'w wojsku'],
    ['kolor oczu', 'kolor włosów', 'rysy', 'charakter', 'mimikę', 'chorobę'],
    ['dobry', 'szampański', 'zły', 'wisielczy', 'czarny', 'sytuacyjny'],
    ['próbki kosmetyków', 'kalendarze', 'płyty', 'biżuteria', 'książki'],
    ['uczeń', 'praktykant', 'stażysta'],
    ['urodzinowe', 'ślubne', 'na chrzciny', 'imieninowe', 'urodziny dziecka', 'z podziękowaniami'],
    ['telefoniczny', 'soli', 'wysokiego napięcia', 'graniczny', 'ognia', 'dymu'],
    ['rolniczej', 'wojskowej', 'muzycznej', 'ekonomicznej', 'teatralnej', 'sztuk pięknych'],
    ['odpowiedź', 'jama', 'egzamin'],
    ['masło', 'śmietanę', 'ser', 'jogurt', 'kefir', 'maślankę'],
    ['głowy', 'nosa', 'buta', 'drzewa', 'palca', 'góry lodowej'],
    ['Bug', 'Bzura', 'Biebrza', 'Brda', 'Bóbr', 'Bystrzyca'],
    ['palenia', 'wychylania się', 'wyrzucania przez okno', 'opierania się o drzwi', 'wsiadania po sygnale'],
    ['dziennikarz', 'prawnik', 'nauczyciel'],
    ['park', 'las', 'stare miasto', 'nad wodą', 'łąka'],
    ['kaczek', 'gęsi', 'przepiórek', 'indyków', 'strusi'],
    ['święconkę', 'pisanki', 'ciasta', 'mięsa', 'ryby'],
    ['słońce', 'chmury', 'gwiazdy', 'księżyc', 'samoloty'],
    ['pisklę', 'żółtko', 'białko', 'żółwia', 'zarodek', 'węża'],
    ['w kubku', 'w torebce', 'w puszce', 'w szklance', 'w filiżance', 'w imbryku'],
    ['wniosku', 'wprawy', 'porozumienia', 'siebie', 'głosu', 'ładu'],
    ['świeże', 'kiszone', 'konserwowe', 'mizerii', 'zupy'],
    ['chleba', 'papierosów', 'cukru', 'mąki', 'warzyw', 'alkoholu'],
    ['gwizdnąć', 'buchnąć', 'zwędzić', 'zakosić', 'podprowadzić'],
    ['rzepa', 'ziemniak', 'seler'],
    ['kasa', 'poczekalnia', 'rozkład jazdy', 'zegar', 'bar', 'toaleta'],
    ['słowik', 'wróbel', 'kogut', 'kukułka', 'dzięcioł', 'czajka'],
    ['lekarz', 'nauczyciel', 'ksiądz', 'pielęgniarka', 'ratownik medyczny'],
    ['Etna', 'Wezuwiusz', 'Stromboli'],
    ['jeż', 'kret', 'jamnik', 'żółw', 'chomik', 'mysz'],
    ['państwa', 'balu', 'pszczół', 'piękności', 'nauk', 'mrówek'],
    ['Łódź', 'Łomża', 'Łowicz', 'Łeba', 'Łęczyca', 'Łańcut'],
    ['gniazdek', 'noży', 'kuchenki', 'zapałek', 'żelazka'],
    ['znak zodiaku', 'Jańcio', 'Szuwarek'],
    ['pieniądze', 'złoto', 'miłość', 'dokumenty', 'jedzenie', 'informacje'],
    ['dyskoteka', 'pub', 'dworzec', 'ulica', 'szkoła', 'lotnisko', 'stadion'],
    ['Biblia', 'słownik', 'encyklopedia', 'Pan Tadeusz', 'kucharska', 'Trylogia'],
    ['flejtuch', 'bałaganiarz', 'niechluj', 'brudas', 'niedbaluch'],
    ['życie', 'ołów', 'żelazo', 'kamień'],
    ['koza', 'wilk', 'kruk', 'kot', 'koń', 'rak'],
    ['zwierzęta', 'lasy', 'mienie', 'zabytki', 'życie', 'zdrowie'],
    ['Bielsko Biała', 'Biała Podlaska', 'Gorzów Wielkopolski', 'Nowy Sącz', 'Zielona Góra'],
    ['grzyby', 'jagody', 'szyszki', 'poziomki', 'jeżyny', 'żołędzie'],
    ['Piłsudski', 'Wałęsa', 'Wołodyjowski', 'Zagłoba', 'Stalin', 'Rumcajs'],
    ['cytryna', 'deszcz', 'ogórki', 'kapusta', 'mina', 'szczaw', 'kwasek', 'trwała'],
    ['huśtawka', 'piaskownica', 'karuzela', 'zjeżdżalnia', 'drabinki'],
    ['prace', 'rozkaz', 'polecenie', 'utwór', 'zadanie', 'testament'],
    ['kieszeń', 'suwak', 'guziki', 'falbankę', 'rozmiar', 'fason'],
    ['kierowca', 'taksówkarz', 'lekarz', 'ksiądz', 'motorniczy', 'dziennikarz', 'maszynista'],
    ['broda', 'wąsy', 'brwi', 'rzęsy'],
    ['bieganie', 'jazda na rowerze', 'pływanie'],
]

Points = [
    [42, 17, 12, 9, 8, 6],
    [42, 17, 15, 11, 9, 6],
    [34, 26, 17, 12, 7],
    [51, 26, 17],
    [33, 22, 16, 9, 8, 6],
    [27, 23, 17, 14, 8, 6],
    [34, 19, 15, 12, 8, 6],
    [30, 22, 18, 13, 10],
    [45, 38, 10],
    [29, 27, 13, 10, 8, 6],
    [30, 21, 18, 11, 9, 6],
    [28, 27, 17, 9, 8, 6],
    [38, 33, 21],
    [31, 20, 16, 12, 10, 7],
    [22, 20, 18, 15, 12, 8],
    [34, 23, 13, 11, 8, 7],
    [30, 24, 17, 13, 11],
    [37, 32, 25],
    [31, 28, 16, 10, 8],
    [32, 28, 16, 12, 10],
    [28, 25, 20, 13, 10],
    [25, 23, 19, 16, 11],
    [31, 22, 16, 11, 8, 6],
    [26, 21, 17, 13, 11, 8],
    [30, 23, 15, 11, 10, 6],
    [30, 26, 16, 12, 10],
    [28, 17, 16, 12, 9, 8],
    [29, 26, 19, 13, 8],
    [36, 29, 25],
    [25, 23, 18, 14, 9, 6],
    [31, 20, 17, 13, 8, 6],
    [30, 27, 19, 10, 6],
    [45, 35, 13],
    [27, 21, 16, 13, 9, 8],
    [31, 19, 15, 13, 9, 8],
    [21, 20, 19, 14, 13, 6],
    [25, 23, 20, 18, 7],
    [63, 18, 9],
    [28, 25, 14, 12, 9, 6],
    [28, 24, 12, 10, 8, 7, 5],
    [29, 23, 16, 10, 8, 6],
    [35, 25, 17, 12, 7],
    [29, 27, 25, 14],
    [34, 19, 16, 11, 8, 8],
    [36, 18, 15, 9, 8, 6],
    [32, 23, 16, 13, 8],
    [48, 15, 12, 10, 6, 5],
    [26, 22, 17, 12, 7, 5],
    [35, 13, 12, 10, 8, 7, 5, 5],
    [27, 25, 18, 13, 11],
    [26, 20, 16, 14, 12, 5],
    [26, 23, 15, 11, 9, 7],
    [20, 18, 16, 14, 11, 9, 7],
    [36, 29, 16, 15],
    [37, 34, 23],
]

Hints = [
    ['potomek dinozaurów', 'plujka', 'np. rusałka pawik', 'wisi głową do dołu', 'zjadaczka mszyc'],
    ['impulsywny samochwała', 'właściciel zamku w Odrzykoniu', 'mocium panie', 'wdowa', 'sekretarz Cześnika', 'zakochana w Wacławie'],
    ['stój wyprostowany', 'noga w bok', 'do przodu', 'już nie siedzimy', 'na ziemię'],
    ['stolica Szwecji', 'stolica Norwegii', 'stolica Danii'],
    ['w jednej ławce', 'na uczelni', 'hej ho .... by się szło', 'przy zabawie grabkami i foremkami', 'baczność'],
    ['niebieskie, zielone, piwne', 'blond, rude', ' .... twarzy', 'spokojny, gwałtowny', 'ruchy mięśni twarzy', 'kiedy coś dolega'],
    ['wszystko dobrze', 'jak musujące wino', 'oj jest źle', 'z szubienicą', 'nie biały', 'w zależności od sytuacji'],
    ['mini opakowania kremów lub perfum', 'miesiące i dni na kartkach', 'CD lub DVD', 'kolczyki, pierścionki, naszyjniki', 'woluminy'],
    ['w szkole', 'uczy się praktyki', 'na stażu'],
    ['sto lat', 'z obrączkami', 'na pierwszy sakrament', 'na święto imienia', 'pojawienie się nowego członka rodziny', '...... za coś'],
    ['halo halo, mówi się', 'słony', 'wysokie słupy z prądem', 'między państwami', 'gorący żywioł', 'nie ma .... bez ognia'],
    ['z traktorem', 'z czołgiem', 'z gitarą', 'z pieniądzem', 'z repertuarem', 'z malarstwem'],
    ['na sprawdzianie', 'inaczej dziura', 'kontrola wiadomości'],
    ['robi się w maselnicy', 'pochodzi z warstwy górnej odwirowanego mleka', 'np. żółty, pleśniowy,' 'z kulturami bakterii', 'musujący napój z mleka fermentowanego', 'bogata w lecytynę, białka i sole mineralne'],
    ['na górze człowieka', 'na środku twarzy', 'ubranie stopy', 'roślina z gałęziami', 'pięć u dłoni', 'pływający kawał lodu'],
    ['czwarta najdłuższa rzeka w Polsce', 'sławna bitwa nad ..... we wrześniu 1939', ' w północno-wschodniej Polsce, prawy dopływ Narwi', 'w północnej Polsce, lewy dopływ Wisły', 'w południowo-zachodniej Polsce, największy z lewobrzeżnych dopływów Odry', 'płynie w województwie dolnośląskim, lewy dopływ Odry'],
    ['inaczej jarania', '...... przez okno', 'pozbywania się śmieci poza pociąg', 'ponieważ mogą się otworzyć', 'kiedy już zadzwoni'],
    ['w redakcji', 'w kancelarii', 'w szkole'],
    ['zieleń w mieście', 'skupisko drzew za miastem', 'zabytkowa część miasta', 'np. nad rzeką, jeziorem, morzem', 'bez drzew, za miastem, mnóstwo trawy'],
    ['kwa kwa', 'gę, gę', 'płowobrązowy wędrowny ptak', 'gulgulgul', 'pędziwiatr'],
    ['w koszyku', 'kolorowe jajka', 'słodkie, puszyste', 'np. wieprzowina', 'np. dorsz'],
    ['świeci za dnia', 'pierzaste, kłębiaste, warstwowe', 'mnóstwo ich w nocy', 'satelita Ziemi', 'maszyny latające ze skrzydłami'],
    ['małego ptaka', 'żółte', 'białe', 'małego, ze skorupą', 'na początku życia', 'gada bez kończyn'],
    ['naczynie codzienne', 'ze sznurkiem i karteczką', 'kiedy przechowywana', 'naczynie szklane', 'naczynie eleganckie', 'podczas zaparzania'],
    ['po uwzględnieniu faktów', 'kiedy się coś robi wiele razy', 'jak strony się zgadzają', 'własnej osoby', 'kiedy uda się coś powiedzieć', 'porządku'],
    ['odrazu po zerwaniu', 'kwaśne, w słoiku', 'z octem, w słoiku', 'pokrojone ze śmietaną', 'w talerzu gorącej ....'],
    ['naszego, codziennego', 'śmierdziuchów do ciągania', 'białego, słodkiego, sypkiego', 'białej, sypkiej, do wypieków', 'np. kalafior, pomidor, sałata', 'po nim nie mozna prowadzić auta'],
    ['jak na gwizdku', 'buch buch', 'prawie jak uwędzić', 'ale nie kosą', 'jak dziewczynę pod dom'],
    ['ciągną i ciągną, wyciągnąć nie mogą', 'inaczej kartofel', 'a to feler, westchnął ......'],
    ['.... biletowa', 'do czekania', 'rozpiska z godzinami', 'ze wskazówkami', 'tam można coś zjeść', 'ustronne miejsce'],
    ['szary, pięknie śpiewający', 'lepszy w garści', 'kukuryku', 'podrzuca swoje jajka', 'doktor drzew', 'mieszka na podmokłej łące'],
    ['w białym fartuchu', 'w szkole', 'w kościele', 'w czepku na głowie','w karetce'],
    ['rodzaj żeński, na Sycylii', 'zniszczył Pompeje', 'w archipelagu Wysp Liparyjskich'],
    ['tupta nocą', 'ryje korytarze w ziemi', 'długi pies', 'ze skorupą na grzbiecie', 'syryjski, dżungarski, chiński', 'szara'],
    ['inaczej kraju', 'wielkiej imprezy', 'miodnych', 'ładności', 'jest nią matematyka', 'czerwonych, czarnych, faraona'],
    ['łajba w środku Polski', 'we wschodniej Polsce, jest tam browar', 'stamtąd wody, soki, napoje', 'nad morzem', 'stąd diabeł Boruta', "położone w województwie podkarpackim"],
    ['w nich prąd', 'do krojenia', 'urządzenie do gotowania', 'w pudełku, drewienka z siarką', 'do prasowania'],
    ['w horoskopie', 'w filmie, grany przez Franciszka Pieczkę', 'kręcił z Muchomorkiem'],
    ['kasa, hajs', 'gold', '<3', 'papiery', 'czy nie zatrute', 'wiadomości'],
    ['tam się tańcuje przy głosnej muzyce', 'tam się pije', 'z pociągami lub autobusami', 'jeżdżą po niej samochody', 'korytarze, klasy i mnóstwo dzieci', 'startują tam samoloty', 'tutaj rozgrywają się mecze'],
    ['Stary i Nowy Testament', 'np. ortograficzny', 'kompendium wiedzy w formie artykułów hasłowych', 'poemat epicki Adama Mickiewicza', 'z przepisami', 'Ogniem i Mieczem + Potop + Pan Wołodyjowski'],
    ['ale fleja', 'robi bałagan', 'niechlujny', 'brudny', 'nie dba'],
    ['Edyta Geppert śpiewała, że je kocha', 'miękki, plastyczny metal', 'kuj je, póki gorące', 'twardy jak .....'],
    ['przyszła do woza', 'nosił razy kilka', 'jeden drugiemu oka nie wykole', 'jaki jest, każdy widzi', 'ryba na bezrybiu'],
    ['te co skaczą i pływają', 'mnóstwo drzew', 'rzeczy, które mamy', 'np. stare budynki', 'Edyta Geppert śpiewała, że je kocha', 'śmiech to .....'],
    ['B****** B****', 'B**** P*******', 'G***** W***********', 'N*** S***', 'Z****** G***'],
    ['kapelusz i nóżka', 'czarne, okrągłe, na krzaczkach', 'w nich nasiona drzew', 'malutkie truskawki', 'czarne maliny', 'z dębu'],
    ['naczelnik państwa', 'nie chcę ale muszę', 'mały rycerz', 'herbu w czele', 'wujek Józef ze wschodu', 'tata Cypiska'],
    ['żółty owoc', 'woda z nieba', 'kiedy kiszone', 'kiedy kiszona', 'grymas twarzy', 'zjadamy liście, można zrobić zupę', '..... cytrynowy', 'chemiczna obróbka pasm włosów'],
    ['do przodu, do tyłu', 'zabawa z grabkami i foremkami', 'kręcimy się w kółko', 'jazda z góry na dół', 'wspinamy się'],
    ['zarobkowe', 'baczność', 'służbowe', 'np. piosenka', 'w zeszycie lub ćwiczeniach', 'ostatnia wola'],
    ['do trzymania różnych rzeczy', 'rozpina się i zapina', 'zapinane jeden po drugim', 'ozdoba z materiału', 'M, L, XL', 'krój'],
    ['prowadzący auto, autobus', 'w taxi', 'w gabinecie', 'w kościele', 'prowadzi tramwaj', 'w redakcji', 'kieruje pociągiem'],
    ['jak u Rumcajsa', 'pod nosem', 'mogą być także narysowane', 'do trzepotania'],
    ['na piechotę tylko szybciej', 'na dwóch kółkach', 'w wodzie'],
]