Colors = [
    'Porzeczkowi', 'Śliwkowi', 'Musztardowi', 'Kalafiorowi', 'Niebiescy', 'Miętowi', 'Pomarańczowi', 'Karmazynowi', 'Kobaltowi',
    'Limonkowi', 'Harnaś Rules', 'Żubrówka Team', 'Fani Erepublik', 'Plato To Penis'    
]

Puns = [
    'Wiecie dlaczego bocian stoi na jednej nodze?\nBo jakby ja podniósł to by sie na dziób wywalił.',
    'Skąd pochodzi random.w?\nZ Bytomia.',
    'Po czym jest maxiu?\nPo krokodylu.',
    'Dlaczego w Białymstoku nie nosi sie jajek na święcenie?\nBo Uzury je Zezre.'
]

Questions = [
    "Dotychczasowi dowódcy TGS - nicki z profila z gry.",
    "Jaki jest Uzury?",
    "Gracze którzy otrzymali Order Zasłużony dla TGS - nicki z profila z gry?",
    "Jakie jest auto Uzurego?",
    "Jakie nagrody są w standardowym Weekly Challenge w eRepublik?",
    "Ulubione Uzurego postacie z bajek i literatury dziecięcej.",
    "Prawdziwy Tygrys jest ....",
    "Jakie są kolory aut?",
    "Skróty stosowane w eRepublik.",
    "Kto tak bardzo chce przejść do TGS że aż piszczy.",
    "Bóg wyznawany w antycznej Grecji.",
    "Polski klub piłkarski (trzeba podać pełną nazwę w mianowniku, np. Szombierki Bytom).",
    "Polska komedia z okresu 1995-2005.",
    "Antyczny filozof.",
    "Wymień podgatunki tygrysa",
    "Co trzeba zrobić w eRepublik codziennie bez wyjątku?",
    "Więcej niż jedna flaszka to?",
    "Jakim przymiotnikiem możesz określić swoją fabrykę broni Q7, ale nie swoją partnerkę (jeśli ci życie miłe).",
    "Stworzenie na literę T",
    "Wymień partie polityczne w ePolsce (skrót nazwy)",
    "Wymień prezydentów ePl.",
    "W czym zdarza nam się stać (forma odpowiedzi - w ....)",
    "Co oprócz materiałów budowlanych trzeba mieć aby wybudować dom?",
    "Co można robić głęboko?",
    "Odgłos wydawany przez ptactwo",
    "Jaka może być gałka?",
    "Sklep w którym kupimy konkretny rodzaj produktów spożywczych?",
    "Przykład stołu przy którym się nie je",
    "Jak inaczej powiesz, że czegoś nie lubisz?",
    "Zwierze które nosi ludzi na grzbiecie.",
    "Coś towarowego.",
    "Podaj przykład jadalnego oleju.",
    "Czego jeden człowiek może udzielić drugiemu?",
    "Kto miewa dyżury?",
    "Jak nazywamy wzniesienie terenu?",
    "Wymień zwierzę które nie ma problemu z poruszaniem się w ciemności.",
    "Element garderoby który kojarzy się z zimą.",
    "Przykład jednośladu",
    "Roślina używana w dekoracjach bożonarodzeniowych, oprócz choinki",
    "Dekoracyjny dodatek do prezentu.",
    "Zwierzę które kojarzy się ze świętami Bożego Narodzenia.",
    "Co niematerialnego można ofiarować bliskim?",
    "Co porusza się miarowo do przodu i do tyłu?",
    "Dodatek do zupy",
    "Stolica europejska na literę B.",
    "Sprzęt wykorzystywany na wykładach.",
    "Wymień stworzenie którego nazwa zaczyna się na ku.",
    "Dokąd nocą tupta jeż?",
    "Co można uprawiać w ogródku?",
]

Answers = [
    ['Uzury Zezre', 'Nowixon', 'DonaldMcKwacz', 'maxi1994', 'ShiroToAka', 'Levstangor', 'Gregoric', 'kameroool', 'Jan Marten'],
    ['przystojny', 'mądry', 'bystry', 'dobry'],
    ['Uzury Zezre', 'Nowixon', 'DonaldMcKwacz', 'maxi1994', 'kooteepeee', 'ShiroToAka', 'Levstangor', 'Gregoric', 'anon3525', 'PwneDPL', 'Vogel Serapel', 'Harab Serapel'],
    ['czerwone', 'stare', 'biedne', 'poobijane', 'na ropę'],
    ['punkty odnawiania energii', 'batony', 'bilety', 'miejsca magazynowe', 'boostery'],
    ['Emil z Lonnebergi', 'Pinky Pie', 'Muminki'],
    ['dzielny', 'prawy', 'szybki', 'hojny'],
    ['szary', 'srebrny', 'czarny', 'biały', 'czerwony', 'niebieski', 'bordowy', 'żółty'],
    ['MUDO', 'PP', 'WC', 'SH', 'BH', 'RH', 'WRAW', 'CP'],
    ['Magic', 'Scool', 'Gacie', 'każdy'],
    ['Zeus', 'Posejdon', 'Hades', 'Artemida', 'Atena'],
    ['Legia Warszawa', 'Lech Poznań', 'Wisła Kraków', 'Górnik Zabrze', 'Widzew Łódź'],
    ['Nic śmiesznego', 'Dzień Świra', 'Chłopaki nie płaczą', 'Poranek Kojota', 'Kiler'],
    ['Seneka', 'Platon', 'Sokrates', 'Arystoteles', 'Epikur'],
    ['bojówkowy', 'syberyjski', 'bengalski', 'indochiński', 'sumatrzański', 'chiński', 'malajski'],
    ['MUDO', 'trenować', 'pracować'],
    ['piąteczek', 'impreza', 'alkoholizm', 'lama'],
    ['sprzedana', 'nieopłacalna', 'wielka'],
    ['tygrys', 'tarpan', 'tchórz', 'traszka', 'tukan', 'tuńczyk', 'trzmiel', 'tarantula'],
    ['PI', 'PPP', 'ND', 'PWL', 'PDL', 'Tygryski'],
    ['Kherehabath', 'Rapaport', 'StrozeR', 'Sarandir', 'Yogobella'],
    ['w kolejce', 'w korku', 'w drzwiach', 'w przejściu', 'w oknie', 'w kącie'],
    ['pieniądze', 'działkę', 'pozwolenie', 'projekt', 'ekipę', 'umiejętności'],
    ['wzdychać', 'spać', 'wierzyć', 'kopać', 'zaciągać się', 'nurkować'],
    ['gdakanie', 'pianie', 'kwakanie', 'gęganie', 'gulgot'],
    ['oczna', 'muszkatałowa', 'meblowa'],
    ['warzywny', 'mięsny', 'piekarnia', 'nabiałowy', 'cukiernia', 'garmażeria'],
    ['bilardowy', 'roboczy', 'pingpongowy', 'kreślarski', 'do masażu', 'operacyjny'],
    ['nie przepadam', 'nienawidzę', 'nie cierpię', 'nie znoszę', 'nie trawię', 'nie toleruję'],
    ['koń', 'wielbłąd', 'osioł', 'słoń', 'kuc'],
    ['pociąg', 'winda', 'znak'],
    ['słonecznikowy', 'oliwa z oliwek', 'rzepakowy', 'lniany', 'kokosowy', 'arachidowy'],
    ['pomocy', 'odpowiedzi', 'rady', 'pozwolenia', 'pożyczki', 'wywiadu'],
    ['lekarz', 'pielęgniarka', 'nauczyciel', 'policjant', 'dziennikarz', 'uczeń'],
    ['góra', 'wzgórze', 'pagórek', 'górka', 'wyżyna'],
    ['nietoperz', 'kot', 'sowa'],
    ['czapka', 'sweter', 'skarpeta', 'rękawiczka', 'szalik'],
    ['rower', 'motocykl', 'skuter', 'hulajnoga'],
    ['jemioła', 'gwiazda betlejemska', 'ostrokrzew'],
    ['papier', 'torebka', 'kokarda', 'wstążka', 'bilecik'],
    ['renifer', 'wół', 'osioł', 'wielbłąd', 'karp'],
    ['miłość', 'czas', 'uwagę', 'pamięć', 'opiekę'],
    ['wahadło', 'huśtawka', 'dzwon'],
    ['śmietana', 'ryż', 'makaron', 'grzanka', 'groszek ptysiowy', 'ziemniaki'],
    ['Berlin', 'Budapeszt', 'Bruksela', 'Bratysława', 'Belgrad', 'Bukareszt'],
    ['rzutnik', 'komputer', 'tablica', 'mikrofon', 'wskaźnik', 'projektor'],
    ['kura', 'kukułka', 'kuropatwa', 'kuna', 'kuc'],
    ['do domu', 'wklepać niedźwiedziowi', 'do roboty', 'na Jeżyce', 'do Dziub Dziuba'],
    ['marihuanę', 'seks', 'politykę', 'cebulę', 'baobaby'],
]

Points = [
    [20, 20, 20, 20, 20, 20, 20, 20, 20],
    [20, 20, 20, 20, 20],
    [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
    [30, 30, 30, 30, 30],
    [30, 30, 30, 30, 30],
    [40, 40, 40],
    [30, 30, 30, 30],
    [31, 27, 18, 15, 12, 10, 8, 5],
    [25, 25, 18, 15, 15, 15, 10, 10],
    [33, 33, 33, 133],
    [30, 28, 16, 14, 12],
    [40, 20, 17, 13, 10],
    [40, 35, 30, 25, 20],
    [40, 28, 22, 16, 14],
    [33, 22, 18, 8, 7, 7, 5],
    [60, 25, 15],
    [69, 20, 10, 1],
    [50, 30, 20],
    [50, 11, 9, 8, 7, 6, 5, 4],
    [35, 20, 18, 12, 10, 5],
    [35, 30, 20, 10, 5],
    [28, 24, 15, 11, 8, 6],
    [29, 18, 15, 13, 10, 8],
    [30, 24, 15, 11, 8, 6],
    [28, 22, 15, 14, 10],
    [44, 31, 25],
    [23, 21, 17, 15, 11, 8],
    [31, 22, 14, 10, 9, 7],
    [28, 25, 14, 12, 8, 7],
    [44, 20, 15, 12, 9],
    [49, 25, 19],
    [32, 21, 17, 11, 8, 6],
    [30, 19, 13, 12, 10, 9],
    [36, 18, 14, 11, 8, 6],
    [33, 26, 15, 11, 9],
    [44, 28, 21],
    [29, 27, 16, 15, 7],
    [33, 28, 21, 14],
    [41, 34, 17],
    [32, 25, 18, 11, 6],
    [41, 20, 17, 10, 8],
    [32, 24, 18, 12, 8],
    [43, 33, 19],
    [28, 21, 20, 9, 7, 6],
    [32, 19, 18, 10, 8, 7],
    [23, 21, 17, 15, 11, 7],
    [21, 21, 18, 16, 14],
    [20, 20, 20, 20, 20],
    [20, 20, 20, 20, 20],
]

Hints = [
    ['U**** Z****', 'N******', 'D*****M*K****', 'm***1***', 'S****T*A**', 'L*********', 'G*******', 'k********', 'J** M*****'],
    ['ach jaki piękny', 'ma się ten rozumek', 'jak woda w górskim strumyku', 'niczym truskawki i czekolada'],
    ['U**** Z****', 'N******', 'D*****M*K****', 'm***1***', 'k*********', 'S****T*A**', 'L*********', 'G*******', 'a***3***', 'P***D**', 'V**** S******', 'H**** S******'],
    ['jak korale', 'ma swoje lata', 'okrutnie traktowane', 'stuknięcie tu stuknięcie tam', 'nie na benzynę'],
    ['+1 - coraz ich więcej', 'pyszne i pełne energii', 'do podróżowania', 'można więcej gromadzić', 'ulepsza pukawki'],
    ['często siedzi w drewutni', 'różowa w My Little Pony', 'cieszą się tym że im chmurki bieleją o świcie'],
    ['odważny', 'nie lewy', 'jak struś pędziwiatr', 'potrafi sypnąć walutą'],
    ['jak życie i papier toaletowy', 'kolor medalu za drugie miejsce', 'jak smoła', 'jak chmurki na niebie', 'jak burak', 'kolor nieba', 'po królewsku', 'kolor słoneczka'],
    ['rozkazy w bojówce', 'punkty za bicie', 'tygodniowe wyzwanie', 'medal za samoloty', 'medal za bicie w ground', 'medal za wpakowanie się do ramki', 'materiał na tanki', 'prezydę'],
    ['siedzi sam w Magicznym Domu', 'kaczor na awatarze', 'Spodnie', 'no przecież wszyscy'],
    ['władca niebios', 'władca mórz', 'władca podziemi', 'bogini łowów', 'bogini wojny'],
    ['niektórzy ich nie lubią', 'duma Wielkopolski', 'biała gwiazda', 'klub ze Śląska z największą liczbą wygranych mistrzostw', 'kiedyś grał w Lidze Mistrzów a teraz pałęta się po dołach'],
    ['zawsze byłem drugi', 'nie udało mi się życie', 'po tym co tutaj zobaczyłem, nie wiem czy chciałbym ubić z tobą muchę w kiblu', 'młody kojot jest w stanie nawet odgryźć sobie nogę aby nie dać złapać się wąsatemu Meksykaninowi', 'tu Ryba wzywam cię akwarium'],
    ['rzymski stoik', 'założyciel pierwszej akademii w Europie', 'on nic tak naprawdę nie wiedział, tak jak i Wy', 'pierwotnie uczeń Platona, stworzył swoją własną szkołę', 'Cieszmy się z małych rzeczy? Raczej obetnijmy swoje oczekiwania.'],
    ['prosto z TGS', 'strasznie zimno', 'jak naród w Bangladeszu', 'Birma, Laos, Tajlandia, Wietnam, Kambodża', 'Wyspa w Archipelagu Malajskim, w całości należy do Indonezji.', 'najliczniejszy naród na świecie', 'obok Indonezji'],
    ['dostaje się za to batona', 'ćwiczymy', 'hej ho, hej ho, do .... by się szło'],
    ['po czwartku nareszcie', 'głośno i wesoło', 'mamy problem', 'zagubiony', 'więcej niż jedno zwierzę'],
    ['kasa wzięta', 'za dużo kasy idzie', 'ogromna'],
    ['taki jak w TGS', 'konik i auto', 'ktoś strachliwy', 'mały płaz ogoniasty', 'ptak z wielkim dziobem', 'wędrowna ryba', 'gruby, podobny do pszczoły', 'duży pająk'],
    ['pierwsza w National rank', 'druga w National rank', 'trzecia w National rank', 'czwarta w National rank', 'piąta w National rank', 'też tygryśna'],
    ['K*********h', 'R*******t', 'S*****R', 'S******r', 'Y*******a'],
    ['na przykład po cukier', 'w drodze do domu', 'między pomieszczeniami', 'trochę zawadzamy', 'podpatrujemy sobie', 'za karę'],
    ['na drobne wydatki', 'miejsce pod dom', 'załatwia się w urzędzie', 'od projektanta', 'z majstrem na czele', 'to co sam umiesz'],
    ['och, ach', 'chrapu chrap', 'np. w boga', 'szpadlem', 'papierosem', 'pod wodą'],
    ['kura', 'kogut', 'kaczka', 'gęś', 'indyk'],
    ['w twarzy', 'przyprawa', 'do otwierania drzwiczek w szafce'],
    ['marchewka i pomidor', 'łopatka i szynka', 'chleb i bułki', 'masło i ser', 'słodko', 'pasztety, sałatki, dania gotowe'],
    ['toczą się kule', 'np. w warsztacie', 'paletki i piłeczka', 'do rysowania', 'z olejkami', 'skalpel tu działa'],
    ['przepadłem', 'kocham i .....', 'cierp cierp', '..... coś ze schodów', 'jak w żołądku', 'coś z tolerancją'],
    ['kary, gniady i siwek', 'na pustyni', 'kłapouchy', 'Trąbalski', 'mały koń'],
    ['na przedzie lokomotywa', 'jeździ w górę i w dół', 'jak ten co stoi przy ulicy'],
    ['żółte, duże kwiaty', 'śródziemnomorska', 'kwitnie na żółto', 'siemię ....', 'także wiórki', 'orzeszki np. solone'],
    ['ratunku', 'na pytanie', ' dobre dla gromady', 'np. na budowę', 'kasa, kasa', 'rodzaj rozmowy'],
    ['w szpitalu', 'na oddziale', 'w szkole', 'na komendzie', 'w redakcji', 'przy gąbce do ścierania tablicy'],
    ['wielka, wysoka', '.... numer 105', 'murek, sznurek, .....', 'wielka i wysoka zdrobniale', 'wysoko na większym terenie'],
    ['do góry nogami w jaskini', 'pies i ....', 'mądra głowa'],
    ['na głowie', 'różowy u Gruchy', 'jedna często gubi się w praniu', 'na rękę', 'wokół szyi'],
    ['z pedałami', 'np. Honda', 'mały motocykl', 'hulaj dusza'],
    ['pod nią się całują', 'z czerwonymi kwiatami', 'nie tępy krzew'],
    ['kolorowy wokół pudełka', 'z uchwytami, w środku prezent', 'czerwona na pudełku', 'owija papier', 'np. z życzeniami'],
    ['ciągnie sanie', 'silny, łagodny i powolny', 'kłapouchy', 'z garbami', 'pływa w wannie'],
    ['<3', 'odmierza go zegar', 'jak jest się skupionym', 'ze wspomnieniami', 'np. pomoc w codzienności'],
    ['ciężarek na sznurku', 'na placu zabaw', 'bim bam bom'],
    ['12%, 18%, 30%, 36%', 'jaśminowy, parboiled, brązowy', 'rurki, kolanka, nitki', 'zrobiona z pieczywa', 'kulki z ciasta', 'stonka lubi to'],
    ['Niemcy', 'Węgry', 'Belgia', 'Słowacja', 'Serbia', 'Rumunia'],
    ['żeby rzucić obraz na ścianę', 'np. laptop', 'pisze się na niej kredą', 'żeby było słychać co mówione', 'żeby wskazać', 'rzutnik projekcyjny'],
    ['ko ko ko', 'kuku kuku', 'duży ptak', 'rodzaj ssaka drapieżnego', 'mały koń'],
    ['do chałupy', 'zbić większego', 'na drugą zmianę', 'na jedną z dzielnic Poznania', 'do tego co go nikt nie widział'],
    ['..... leczniczą', 'bara bara', 'poważne rozmowy', 'ze szczypiorem', 'walczył z nimi Mały Książe'],
   ]