Ciekawostki = [
    "Tygrysy to największy gatunek kota na świecie, osiągający do 3,3 metra długości i ważą do 330 kilogramów!",
    "Istnieje sześć charakterystycznych tygrysów: Bengalski, Syberyjski, Indochiński, Syberyjski, Chiński i Malajski. Wymarłe podgatunki obejmują tygrysy: Kaspijski, Balijski, Jawajski i tygrys z Trinil który wymarł 1,2 miliona lat temu.",
    "Tygrysy są łatwo rozpoznawalne dzięki ciemnym pionowym paskom i czerwono-pomarańczowemu futru.",
    "Przy pełnej prędkości, tygrysy mogą osiągać do 65 km/h.",
    "Tygrysy chowają swoje pazury, co sprawia, że są cichymi łowcami.",
    "Tygrysy mają ślinę antyseptyczną. To, co robią po urazie, to lizanie okolicy, aby zapobiec infekcji.",
    "Najczęściej spotykanym tygrysem jest tygrys bengalski.",
    "Paski, które tygrys ma, są tak unikalne, jak odciski palców u ludzi.",
    "Ponad 3 tysiące dzikich tygrysów włóczy się dziś po lasach i sawannach.",
    "Jedno machnięcie przednią ręką Tygrysa wystarczy, by zabić człowieka lub zwierzę, a przynajmniej złamać kości.",
    "Shere Khan był śmiertelnym tygrysem w Księdze Dżungli Rudyarda Kiplinga (1894).",
    "Tylne nogi tygrysa są dłuższe niż przednie, co sprawia, że jest to niezła maszyna do biegania, skakania.",
    "Tygrys może zabić natychmiast jednym ugryzieniem w szyję wbijając się przez rdzeń kręgowy. Tygrys może również udusić swoją ofiarę, ściskając jej gardło przez okres do 10 minut.",
    "W przeciwieństwie do większości członków rodziny kotów, lubią wodę i często ochładzają się w oczkach wodnych lub strumieniach.",
    "Tygrysy są zwierzętami nocnymi. Niekoniecznie jest prawdą, że wszystkie Tygrysy są nocne, ale tak, wolą angażować się w większość swoich zajęć łowieckich w nocy. Tygrysy wolą unikać konfliktów w ciągu dnia, a także patrolować swoje terytorium w nocy.",
    "Tygrysy żyją na wolności od 20-26 lat.",
    "Dorosłe tygrysy na ogół żyją samotnie.",
    "Ryk tygrysa słychać nawet w odległości trzech kilometrów.",
    "W przeciwieństwie do większości innych kotów, tygrysy są wspaniałymi pływakami i faktycznie lubią wodę.",
    "Tygrysy ucztują na wielu zwierzętach, w zależności od ich terytorium. Należą do nich: antylopa, dzik, bawół, wielbłąd, ryba czy koń.",
    "Młode tygrysy rodzą się ślepe i tylko połowa z nich przeżywa. Młode nic nie widzą, podążają tylko za zapachem swojej matki. Ponieważ rodzą się niewidome i nie potrafią nadążyć za matką, większość z nich umiera z głodu lub zimna.",
    "Tygrysy mają ponad 100 pasków, co pomaga tygrysowi wtopić się w długą trawę.",
    "Tygrysy zabiły więcej ludzi niż lwy czy lamparty. W XIX wieku, tygrysy mogły zabić nawet setki tysięcy ludzi.",
    "W folklorze azjatyckim, tygrys jest postrzegany jako przerażające stworzenie, zastępujące wilkołaka.",
    "Młode rodzą się niewidome i otwierają oczy 1-2 tygodnie po urodzeniu.",
    "Młode zaczynają uczyć się polować w wieku sześciu miesięcy, ale pozostają z matkami do ukończenia 18 miesięcy.",
    "Co ciekawe, tygrys może przeżyć dwa tygodnie bez jedzenia.",
    "Potrafią w jednym posiłku zjeść 32 kilogramy mięsa.",
    "Tygrysy są mięsożercami, jedzą tylko mięso.",
    "Co ciekawe, zapach emitowany z moczu Tygrysów pachnie jak maślany popcorn.",
    "Tygrysy mogą łączyć się z innymi dużymi kotami. Jeśli samiec Tygrysa kojarzy się z samicą Lwa, zwierzę hybrydowe jest znane jako Tyglew.",
    "Mniej niż 100 lat temu tygrysy można było znaleźć w całej Azji. Niestety, polowania i utrata siedlisk zagroziły populacji, a obecnie ich zasięg został zmniejszony do około 7 procent ich dawnej wielkości.",
    "Tygrysy są one jednym z chińskich znaków zodiaku.",
    "Tygrysy komunikują się za pomocą oznaczeń zapachowych, sygnałów wizualnych i wielu dźwięków, takich jak ryk, warczenie, jęki czy syczenie.",
    "Hodowla krzyżowa tygrysów jest zakazana na Tajwanie.",
    "Podczas gdy tygrys jest świetnym myśliwym, tylko jedno na każde 20 polowań kończy się zabiciem ofiary. Na obszarach, gdzie ofiar jest mało, jeszcze mniej polowań kończy się sukcesem.",
    "Tygrysy mogą naśladować wołanie innych zwierząt. Tygrysy wydają „pook”, który przypomina dźwięk sambara, który wciąga te niewinne zwierzęta w zasadzkę.",
    "Metoda zabijania ofiary przez tygrysa polega na prześladowaniu jej przed zasadzką i obezwładnieniem, przed ugryzieniem.",
    "Tygrys bengalski jest zwierzęciem narodowym Bangladeszu i Indii.",
    "Ludzkie zachowanie może sprawić, że tygrys poczuje się zagrożony i zaatakuje ludzi.",
    "Tygrysy są samotnymi myśliwymi i na ogół szukają pożywienia samotnie w nocy.",
    "Podczas gdy tygrysy czasami się gromadzą, zazwyczaj żyją samotnie.",
    "Tygrys syberyjski ma około 3000 włosów na jednym centymetrze kwadratowym skóry.",
    "Tygrysy można znaleźć w co najmniej dziewięciu krajach, które obejmują USA, Czechy, Chiny, Iran, Rosja, Indie, ZEA i Argentyna.",
    "Uważa się, że skamieniałe szczątki tygrysów znalezione w niektórych częściach Chin mają 2 miliony lat.",
    "Tygrysy są mocno zagrożonym gatunkiem.",
    "Jest drugim po pumie rekordzistą w skoku wzwyż i drugim po lwie w skoku w dal. Potrafi wyskoczyć na wysokość 5 m a także jednym skokiem pokonać odległość 8-9 m.",
    "Najlepiej rozwiniętym zmysłem tygrysów jest słuch.nWychwytują dźwięki o częstotliwości od 200 Hz do 100 kHz (pięciokrotnie wyższe niż słyszalne przez człowieka).",
    "Zmysł węchu nie należy do wysoko rozwiniętych. Jest słabszy niż u psów. Do rozpoznawania zapachów wykorzystują pomocniczo narząd Jacobsona.",
    "Tygrysy, podobnie jak lwy, otwierają pysk i wysuwają język aby ułatwić dostęp powietrza do receptorów węchowych.",
    "Ryk tygrysa jest tak donośny, że można go usłyszeć z odległości ponad 3 km. W rzeczywistości zasięg ryku jest znacznie większy gdyż tygrysy potrafią wydawać dźwięki (infradźwięki) o jeszcze niższej częstotliwości niż ta słyszalna przez człowieka.",
    "Lev zwany Stangor, który mimo mylnej nazwy należy do tygrysiej rodziny, osiąga powierzchnię złota w magazynie sięgającą 1km^2 a także często miewa sprośne myśli.",
    "Tygrysy jak wszystkie koty posiadają przesłonę migawkową zwaną trzecią powieką.",
    "Tygrysy są świetnymi pływakami, płynąc mogą zabić ofiarę. Potrafią przepłynąć rzekę o szerokości 6-8 km a z nurtem nawet ok 30 km.",
    "Tygrysy mają małe, okrągłe źrenice i żółte tęczówki. Siatkówka oka tygrysa posiada sześciokrotnie więcej niż u człowieka punkcików ( zwanych pręcikami) odpowiedzialnych za widzenie nocne (skotopowe). Pręciki odbierają informację o jasności danego obiektu a nie o barwie. Zwiększona ilość pręcików pozwala im przy prawie całkowitej ciemności dostrzec ruchy przedmiotów i zwierząt. Daje im to ogromną przewagę w ciemnościach i dlatego polują w nocy.",
    "Umaszczenie tygrysów uzależnione jest od pory roku i od podgatunku. Barwa tygrysów bywa od żółtej do czerwonopomarańczowej z wyraźnymi czarnymi pręgami. Brzuch i boki głowy tygrysów są białe.",
    "Owłosienie tygrysów pełni też funkcję zmysłu dotyku. Włosy czuciowe rozłożone są na na całej skórze a wibrysy występują na brwiach, policzkach, na górnej wardze i po obu stronach pyska.",
    "Pręgi tygrysów są jak odciski palców. Nie ma dwóch osobników o takim samym umaszczeniu. Najjaśniejsze pręgi mają tygrysy syberyjskie - brązowe. Pręgi znajdują się również na skórze.",
    "Tygrysy mają wiele odmian barwnych. Znane są tygrysy białe, czarne i niebieskie. Niebieski tygrys zwany jest maltańskim i jest prawdopodobnie odmianą tygrysa bengalskiego. Wszystkie białe tygrysy przebywające w ogrodach zoologicznych pochodzą od jednego ojca o imieniu Mohman. Tygrysy te mają więcej problemów zdrowotnych jak: rozszczepienie wargi i podniebienia, skolioza czy zez. Jest to wynikiem chowu wsobnego, który zapewnia ogrodom zoologicznym białe koty.",
    "W naturze gen warunkujący białą sierść występuje u jednego na dziesięć tysięcy osobników.",
    "Większość tygrysów żyje w lasach tropikalnych, na terenach porośniętych trawami, trzcinami i bambusami.",
    "Rzadko wchodzą na drzewa. Odpoczywają w cieniu pod drzewami a na syberyjskich stepach w rozpadlinach skalnych.",
    "Tygrysy polują na wszelkie zwierzęta niezależnie od wielkości. Jedynie dorosłe, zdrowe nosorożce i słonie potrafią oprzeć się ich żarłoczności. W starciu z niedźwiedziem brunatnym, niedźwiedź często bywa pokonany.",
    "Jednorazowo tygrys zjada 20-35 kg mięsa. Wygłodniały może zjeść do 50 kg. Część niezjedzonego mięsa potrafią ukryć na na następny posiłek.",
    "Samce obejmują tereny o powierzchni 60-100 km2, samice do 20 km2. Terytoria znakowane są moczem, odchodami i zapachami gruczołowymi.",
    "Podstawową jednostką rodzinną jest samica z młodymi. Samce tylko czasami z nimi przebywają.",
    "Tygrysy spacerują tylko w towarzystwie ze sobą spokrewnionym. W przypadku samic jest to matka z córką.",
    "Samice dojrzałość płciową osiągają między 3-4 rokiem życia, samce rok później. Ciąża trwa średnio 104-106 dni, na świat przychodzą 3-4 młode.",
    "Tygrysy żyją 10-15 lat.",
    "Na wolności tygrysy żyją tylko w Azji. Sto lat temu żyło ich ponad 100 tysięcy, obecnie około 4 tysięcy.",
    "Największym wrogiem tygrysa jest człowiek i azjatycka medycyna ludowa. Części ciała tygrysa wykorzystywane są w medycynie ludowej jako afrodyzjaki.",
    "Tygrysy są symbolem kultury Dalekiego Wschodu. Szczególną czcią otaczane są tygrysy białe, które w Chinach są królami zwierząt, w buddyzmie - symbolem gościnności i pobożności, W Japonii - jednym z czterech dobrych duchów.",
    "Tygrys jest jedną z najpopularniejszych maskotek drużyn sportowych.",
    "Międzynarodowy Dzień Tygrysa przypada na 29 lipca."
]