airRanks = {
    1: "Airman",
    2: "Airman 1st Class",
    3: "Airman 1st Class*",
    4: "Airman 1st Class**",
    5: "Airman 1st Class***",
    6: "Airman 1st Class****",
    7: "Airman 1st Class*****",
    8: "Senior Airman",
    9: "Senior Airman*",
    10: "Senior Airman**",
    11: "Senior Airman***",
    12: "Senior Airman****",
    13: "Senior Airman*****",
    14: "Staff Sergeant",
    15: "Staff Sergeant*",
    16: "Staff Sergeant**",
    17: "Staff Sergeant***",
    18: "Staff Sergeant****",
    19: "Staff Sergeant*****",
    20: "Aviator",
    21: "Aviator*",
    22: "Aviator**",
    23: "Aviator***",
    24: "Aviator****",
    25: "Aviator*****",
    26: "Flight Lieutenant",
    27: "Flight Lieutenant*",
    28: "Flight Lieutenant**",
    29: "Flight Lieutenant***",
    30: "Flight Lieutenant****",
    31: "Flight Lieutenant*****",
    32: "Squadron Leader",
    33: "Squadron Leader*",
    34: "Squadron Leader**",
    35: "Squadron Leader***",
    36: "Squadron Leader****",
    37: "Squadron Leader*****",
    38: "Chief Master Sergeant",
    39: "Chief Master Sergeant*",
    40: "Chief Master Sergeant**",
    41: "Chief Master Sergeant***",
    42: "Chief Master Sergeant****",
    43: "Chief Master Sergeant*****",
    44: "Wing Commander",
    45: "Wing Commander*",
    46: "Wing Commander**",
    47: "Wing Commander***",
    48: "Wing Commander****",
    49: "Wing Commander*****",
    50: "Group Captain",
    51: "Group Captain*",
    52: "Group Captain**",
    53: "Group Captain***",
    54: "Group Captain****",
    55: "Group Captain*****",
    56: "Air Commodore",
    57: "Air Commodore*",
    58: "Air Commodore**",
    59: "Air Commodore***",
    60: "Air Commodore****",
    61: "Air Commodore*****",
    62: "Air Vice Marshal",
    63: "Air Vice Marshal*",
    64: "Air Vice Marshal**",
    65: "Air Vice Marshal***",
    66: "Air Vice Marshal****",
    67: "Air Vice Marshal*****",
    68: "Air Marshal",
    69: "Air Marshal*",
    70: "Air Marshal**",
    71: "Air Marshal***",
    72: "Air Marshal****",
    73: "Air Marshal*****",
    74: "Air Chief Marshal",
    75: "Air Chief Marshal*",
    76: "Air Chief Marshal**",
    77: "Air Chief Marshal***",
    78: "Air Chief Marshal****",
    79: "Air Chief Marshal*****",
}