groundRanks = {
    1: "Recruit",
    2: "Private",
    3: "Private*",
    4: "Private**",
    5: "Private***",
    6: "Corporal",
    7: "Corporal*",
    8: "Corporal**",
    9: "Corporal***",
    10: "Sergeant",
    11: "Sergeant*",
    12: "Sergeant**",
    13: "Sergeant***",
    14: "Lieutenant",
    15: "Lieutenant*",
    16: "Lieutenant**",
    17: "Lieutenant***",
    18: "Captain",
    19: "Captain*",
    20: "Captain**",
    21: "Captain***",
    22: "Major",
    23: "Major*",
    24: "Major**",
    25: "Major***",
    26: "Commander",
    27: "Commander*",
    28: "Commander**",
    29: "Commander***",
    30: "Lt Colonel",
    31: "Lt Colonel*",
    32: "Lt Colonel**",
    33: "Lt Colonel***",
    34: "Colonel",
    35: "Colonel*",
    36: "Colonel**",
    37: "Colonel***",
    38: "General",
    39: "General*",
    40: "General**",
    41: "General***",
    42: "Field Marshal",
    43: "Field Marshal*",
    44: "Field Marshal**",
    45: "Field Marshal***",
    46: "Supreme Marshal",
    47: "Supreme Marshal*",
    48: "Supreme Marshal**",
    49: "Supreme Marshal***",
    50: "National Force",
    51: "National Force*",
    52: "National Force**",
    53: "National Force***",
    54: "World Class Force",
    55: "World Class Force*",
    56: "World Class Force**",
    57: "World Class Force***",
    58: "Legendary Force",
    59: "Legendary Force*",
    60: "Legendary Force**",
    61: "Legendary Force***",
    62: "God of War",
    63: "God of War*",
    64: "God of War**",
    65: "God of War***",
    66: "Titan",
    67: "Titan*",
    68: "Titan**",
    69: "Titan***",
    70: "Legend: Battalion I",
    71: "Legend: Battalion II",
    72: "Legend: Battalion III",
    73: "Legend: Battalion IV",
    74: "Legend: Battalion V",
    75: "Legend: Battalion VI",
    76: "Legend: Battalion VII",
    77: "Legend: Battalion VIII",
    78: "Legend: Battalion IX",
    79: "Legend: Battalion X",
    80: "Legend: Battalion XI",
    81: "Legend: Battalion XII",
    82: "Legend: Battalion XIII",
    83: "Legend: Battalion XIV",
    84: "Legend: Battalion XV",
    85: "Legend: Battalion XVI",
    86: "Legend: Battalion XVII",
    87: "Legend: Battalion XVIII",
    88: "Legend: Battalion XIX",
    89: "Legend: Battalion XX",
}